workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    environment:
      groups:
        - ios-signing
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: keychain initialize
      - name: Set up provisioning profile
        script: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          echo $FCI_PROVISIONING_PROFILE | base64 --decode > "$PROFILES_HOME/farova_app_store.mobileprovision"
          echo "Provisioning profile installed"
      - name: Import signing certificate
        script: |
          echo $FCI_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $FCI_CERTIFICATE_PASSWORD
      - name: Install CocoaPods
        script: pod install
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/Farova.xcworkspace" \
            --scheme "Farova" \
            -- \
            DEVELOPMENT_TEAM=4676423LZC \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            "PROVISIONING_PROFILE_SPECIFIER=635c1a79-7daf-4c8e-b162-26b6ea9ed861" \
            SUPPORTS_MACCATALYST=NO
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
